language: python

python:
  - 'pypy3.5'
  - '3.5'
  - '3.6'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

services:
  - mongodb

install:
  - pip install pipenv
  - pipenv install --dev -e .

script:
  - pipenv run pytest --flake8 --cov apistar_mongoengine

after_success:
  - pipenv run coveralls
